data:
  batch_size: 32
  image_size: 128
  mean: 0.9432905912399292
  num_workers: 8
  std: 0.133747398853302
  train_data_path: /homes/kfirs/PycharmProjects/FinalProject/data/data_sets/Development/first_set_204_text_detection_filtering/train
  val_data_path: /homes/kfirs/PycharmProjects/FinalProject/data/data_sets/Development/first_set_204_text_detection_filtering/val
  test_data_path: /homes/kfirs/PycharmProjects/FinalProject/data/data_sets/Development/first_set_204_text_detection_filtering/test
model:
  model_name: CNNModel
  num_classes: 204
module:
  learning_rate: 0.001
trainer:
  max_epochs: 300
  precision: "16-mixed"
